import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const exercises = [
  {
    name: 'Bench Press',
    slug: 'bench-press',
    category: 'CHEST',
    equipment: 'BARBELL',
    difficulty: 'INTERMEDIATE',
    instructions:
      'Lie flat on the bench with your feet firmly planted on the floor. Grip the barbell slightly wider than shoulder-width apart. Unrack the bar and slowly lower it to your mid-chest while keeping your elbows at a 45-degree angle. Press the bar explosively back up to the starting position until your arms are fully extended.',
    targetMuscles: 'Chest, Triceps, Anterior Deltoids',
    setsRecommendation: '3-4',
    repsRecommendation: '8-12',
    restSeconds: 90,
    caloriesBurnEstimate: 120,
  },
  {
    name: 'Incline Dumbbell Press',
    slug: 'incline-dumbbell-press',
    category: 'CHEST',
    equipment: 'DUMBBELL',
    difficulty: 'INTERMEDIATE',
    instructions:
      'Set an incline bench to 30-45 degrees. Sit back with a dumbbell in each hand resting on your thighs. Kick your knees up to bring dumbbells to chest height. Press dumbbells up until arms are straight, then lower with control to upper chest level.',
    targetMuscles: 'Upper Chest, Front Shoulders, Triceps',
    setsRecommendation: '3-4',
    repsRecommendation: '10-12',
    restSeconds: 90,
    caloriesBurnEstimate: 110,
  },
  {
    name: 'Chest Flyes',
    slug: 'chest-flyes',
    category: 'CHEST',
    equipment: 'DUMBBELL',
    difficulty: 'BEGINNER',
    instructions:
      'Lie flat on a bench holding dumbbells above your chest with palms facing each other. Maintain a slight bend in your elbows. Lower dumbbells out in a wide arc until chest is stretched. Squeeze chest to bring dumbbells back together.',
    targetMuscles: 'Pectoralis Major, Anterior Deltoids',
    setsRecommendation: '3',
    repsRecommendation: '12-15',
    restSeconds: 60,
    caloriesBurnEstimate: 80,
  },
  {
    name: 'Push-Ups',
    slug: 'push-ups',
    category: 'CHEST',
    equipment: 'BODYWEIGHT',
    difficulty: 'BEGINNER',
    instructions:
      'Place hands slightly wider than shoulder-width on the floor. Maintain a straight line from head to heels. Lower body until chest nearly touches the floor, then push back up through your palms.',
    targetMuscles: 'Chest, Core, Triceps',
    setsRecommendation: '3-4',
    repsRecommendation: '15-25',
    restSeconds: 60,
    caloriesBurnEstimate: 70,
  },
  {
    name: 'Pull-Ups',
    slug: 'pull-ups',
    category: 'BACK',
    equipment: 'BODYWEIGHT',
    difficulty: 'INTERMEDIATE',
    instructions:
      'Grip the pull-up bar with palms facing away from you, wider than shoulder-width. Pull your chest up toward the bar by driving elbows down. Lower yourself back down with complete control.',
    targetMuscles: 'Latissimus Dorsi, Biceps, Upper Back',
    setsRecommendation: '3-4',
    repsRecommendation: '6-10',
    restSeconds: 90,
    caloriesBurnEstimate: 100,
  },
  {
    name: 'Barbell Bent-Over Row',
    slug: 'barbell-bent-over-row',
    category: 'BACK',
    equipment: 'BARBELL',
    difficulty: 'INTERMEDIATE',
    instructions:
      'Hinge at hips with knees slightly bent and back flat. Grip barbell slightly wider than shoulder width. Pull the bar toward lower chest/upper abdomen. Lower under control.',
    targetMuscles: 'Lats, Rhomboids, Traps, Erector Spinae',
    setsRecommendation: '3-4',
    repsRecommendation: '8-12',
    restSeconds: 90,
    caloriesBurnEstimate: 115,
  },
  {
    name: 'Lat Pulldown',
    slug: 'lat-pulldown',
    category: 'BACK',
    equipment: 'CABLE',
    difficulty: 'BEGINNER',
    instructions:
      'Sit at pulldown machine and grip bar wide. Lean back slightly and pull bar down to upper chest while driving shoulders down and back. Return bar smoothly to starting stretch.',
    targetMuscles: 'Latissimus Dorsi, Teres Major, Biceps',
    setsRecommendation: '3-4',
    repsRecommendation: '10-12',
    restSeconds: 75,
    caloriesBurnEstimate: 90,
  },
  {
    name: 'Overhead Barbell Shoulder Press',
    slug: 'overhead-barbell-shoulder-press',
    category: 'SHOULDERS',
    equipment: 'BARBELL',
    difficulty: 'INTERMEDIATE',
    instructions:
      'Stand upright holding barbell at collarbone level with grip shoulder-width apart. Brace core and press overhead until arms lock out. Lower bar back to collarbones under control.',
    targetMuscles: 'Anterior & Lateral Deltoids, Triceps',
    setsRecommendation: '3-4',
    repsRecommendation: '8-10',
    restSeconds: 90,
    caloriesBurnEstimate: 105,
  },
  {
    name: 'Dumbbell Lateral Raise',
    slug: 'dumbbell-lateral-raise',
    category: 'SHOULDERS',
    equipment: 'DUMBBELL',
    difficulty: 'BEGINNER',
    instructions:
      'Stand with dumbbells at sides. Keeping slight bend in elbows, raise arms out to sides until parallel to floor. Pause briefly at top, then lower with control.',
    targetMuscles: 'Lateral Deltoids',
    setsRecommendation: '3-4',
    repsRecommendation: '12-15',
    restSeconds: 60,
    caloriesBurnEstimate: 60,
  },
  {
    name: 'Barbell Back Squat',
    slug: 'barbell-back-squat',
    category: 'LEGS',
    equipment: 'BARBELL',
    difficulty: 'ADVANCED',
    instructions:
      'Position bar across upper back. Stand with feet shoulder-width apart. Squat down by bending hips and knees until thighs are parallel to ground or lower. Drive up through heels.',
    targetMuscles: 'Quadriceps, Glutes, Hamstrings, Lower Back',
    setsRecommendation: '4',
    repsRecommendation: '6-10',
    restSeconds: 120,
    caloriesBurnEstimate: 150,
  },
  {
    name: 'Romanian Deadlift',
    slug: 'romanian-deadlift',
    category: 'LEGS',
    equipment: 'BARBELL',
    difficulty: 'INTERMEDIATE',
    instructions:
      'Hold barbell at hip height. Hinge hips back while lowering bar along thighs with soft knees. Lower until hamstring stretch is felt, then squeeze glutes to return upright.',
    targetMuscles: 'Hamstrings, Glutes, Lower Back',
    setsRecommendation: '3-4',
    repsRecommendation: '8-12',
    restSeconds: 90,
    caloriesBurnEstimate: 130,
  },
  {
    name: 'Leg Press',
    slug: 'leg-press',
    category: 'LEGS',
    equipment: 'MACHINE',
    difficulty: 'BEGINNER',
    instructions:
      'Sit on machine with feet hip-width apart on sled. Release safety catches and lower weight until knees form 90-degree angle. Press platform back up without locking knees.',
    targetMuscles: 'Quadriceps, Glutes',
    setsRecommendation: '3-4',
    repsRecommendation: '10-15',
    restSeconds: 90,
    caloriesBurnEstimate: 120,
  },
  {
    name: 'Standing Calf Raise',
    slug: 'standing-calf-raise',
    category: 'LEGS',
    equipment: 'MACHINE',
    difficulty: 'BEGINNER',
    instructions:
      'Place balls of feet on platform with heels hanging off. Lower heels into deep calf stretch, then press up high onto toes and hold at peak contraction.',
    targetMuscles: 'Gastrocnemius, Soleus',
    setsRecommendation: '4',
    repsRecommendation: '15-20',
    restSeconds: 60,
    caloriesBurnEstimate: 50,
  },
  {
    name: 'Barbell Biceps Curl',
    slug: 'barbell-biceps-curl',
    category: 'ARMS',
    equipment: 'BARBELL',
    difficulty: 'BEGINNER',
    instructions:
      'Stand holding barbell with underhand grip shoulder-width apart. Keeping elbows tucked at sides, curl weight toward shoulders. Lower under complete control.',
    targetMuscles: 'Biceps Brachii',
    setsRecommendation: '3-4',
    repsRecommendation: '10-12',
    restSeconds: 60,
    caloriesBurnEstimate: 60,
  },
  {
    name: 'Triceps Rope Pushdown',
    slug: 'triceps-rope-pushdown',
    category: 'ARMS',
    equipment: 'CABLE',
    difficulty: 'BEGINNER',
    instructions:
      'Attach rope to high pulley. Keep elbows locked at sides and push rope down while spreading rope ends apart at bottom lockout. Return slowly to 90 degrees.',
    targetMuscles: 'Triceps (Lateral & Medial Heads)',
    setsRecommendation: '3-4',
    repsRecommendation: '12-15',
    restSeconds: 60,
    caloriesBurnEstimate: 60,
  },
  {
    name: 'Hanging Leg Raise',
    slug: 'hanging-leg-raise',
    category: 'CORE',
    equipment: 'BODYWEIGHT',
    difficulty: 'INTERMEDIATE',
    instructions:
      'Hang from pull-up bar. Without swinging, raise legs straight or bent knees up to chest level by flexing abdominals. Lower legs slowly.',
    targetMuscles: 'Lower Rectus Abdominis, Hip Flexors',
    setsRecommendation: '3-4',
    repsRecommendation: '12-15',
    restSeconds: 60,
    caloriesBurnEstimate: 70,
  },
];

const nutrients = [
  { name: 'Iron', unit: 'mg', category: 'Micronutrient', referenceTarget: 18 },
  { name: 'Calcium', unit: 'mg', category: 'Micronutrient', referenceTarget: 1000 },
  { name: 'Potassium', unit: 'mg', category: 'Micronutrient', referenceTarget: 3400 },
  { name: 'Magnesium', unit: 'mg', category: 'Micronutrient', referenceTarget: 400 },
  { name: 'Zinc', unit: 'mg', category: 'Micronutrient', referenceTarget: 11 },
  { name: 'Vitamin A', unit: 'mcg', category: 'Micronutrient', referenceTarget: 900 },
  { name: 'Vitamin C', unit: 'mg', category: 'Micronutrient', referenceTarget: 90 },
  { name: 'Vitamin D', unit: 'mcg', category: 'Micronutrient', referenceTarget: 20 },
  { name: 'Vitamin B6', unit: 'mg', category: 'Micronutrient', referenceTarget: 1.7 },
  { name: 'Vitamin B12', unit: 'mcg', category: 'Micronutrient', referenceTarget: 2.4 },
  { name: 'Folate', unit: 'mcg', category: 'Micronutrient', referenceTarget: 400 },
  { name: 'Selenium', unit: 'mcg', category: 'Micronutrient', referenceTarget: 55 },
];

const foods = [
  {
    name: 'Chicken Breast',
    category: 'Poultry',
    servingSize: 100,
    servingUnit: 'g',
    calories: 165,
    protein: 31,
    carbohydrates: 0,
    fat: 3.6,
    fiber: 0,
    sugar: 0,
    saturatedFat: 1.0,
    sodium: 74,
    ingredients: [{ name: 'Chicken breast' }],
    benefits: ['High in protein', 'Supports daily protein intake', 'Low in carbohydrates', 'Provides vitamin B6', 'Provides selenium'],
    nutrients: { Iron: 1.0, Potassium: 256, Magnesium: 29, Zinc: 1.0, 'Vitamin B6': 0.6, 'Vitamin B12': 0.3, Selenium: 27 },
  },
  {
    name: 'Eggs',
    category: 'Poultry & Dairy',
    servingSize: 100,
    servingUnit: 'g (2 large)',
    calories: 155,
    protein: 13,
    carbohydrates: 1.1,
    fat: 11,
    fiber: 0,
    sugar: 0.6,
    saturatedFat: 3.3,
    sodium: 124,
    ingredients: [{ name: 'Whole egg' }],
    benefits: ['Complete protein source', 'Provides choline', 'Provides vitamin B12', 'Provides selenium', 'Provides healthy fats'],
    nutrients: { Iron: 1.8, Calcium: 56, Potassium: 138, Magnesium: 12, Zinc: 1.3, 'Vitamin A': 160, 'Vitamin D': 2.0, 'Vitamin B6': 0.1, 'Vitamin B12': 0.9, Folate: 47, Selenium: 30.8 },
  },
  {
    name: 'Grilled Salmon',
    category: 'Seafood',
    servingSize: 100,
    servingUnit: 'g',
    calories: 208,
    protein: 20,
    carbohydrates: 0,
    fat: 13,
    fiber: 0,
    sugar: 0,
    saturatedFat: 3.1,
    sodium: 59,
    ingredients: [{ name: 'Salmon' }],
    benefits: ['High in protein', 'Rich in omega-3 fatty acids', 'Provides vitamin B12', 'Provides vitamin D', 'Provides selenium'],
    nutrients: { Iron: 0.5, Calcium: 12, Potassium: 363, Magnesium: 27, Zinc: 0.6, 'Vitamin A': 12, 'Vitamin D': 11.0, 'Vitamin B6': 0.8, 'Vitamin B12': 3.2, Folate: 29, Selenium: 36.5 },
  },
  {
    name: 'Canned Tuna',
    category: 'Seafood',
    servingSize: 100,
    servingUnit: 'g',
    calories: 130,
    protein: 28,
    carbohydrates: 0,
    fat: 1,
    fiber: 0,
    sugar: 0,
    saturatedFat: 0.2,
    sodium: 300,
    ingredients: [{ name: 'Tuna' }],
    benefits: ['High in protein', 'Low in carbohydrates', 'Provides vitamin B12', 'Provides selenium', 'Provides niacin'],
    nutrients: { Iron: 1.0, Calcium: 11, Potassium: 237, Magnesium: 33, Zinc: 0.8, 'Vitamin D': 2.0, 'Vitamin B6': 0.5, 'Vitamin B12': 2.5, Folate: 4, Selenium: 80.4 },
  },
  {
    name: 'Greek Yogurt',
    category: 'Dairy',
    servingSize: 100,
    servingUnit: 'g',
    calories: 59,
    protein: 10,
    carbohydrates: 3.6,
    fat: 0.4,
    fiber: 0,
    sugar: 3.2,
    saturatedFat: 0.1,
    sodium: 36,
    ingredients: [{ name: 'Milk' }, { name: 'Live yogurt cultures' }],
    benefits: ['High in protein', 'Provides calcium', 'Provides vitamin B12', 'Useful for increasing daily protein intake', 'Can contribute to calcium intake'],
    nutrients: { Iron: 0.1, Calcium: 110, Potassium: 141, Magnesium: 11, Zinc: 0.5, 'Vitamin A': 2, 'Vitamin B6': 0.05, 'Vitamin B12': 0.75, Folate: 7, Selenium: 9.7 },
  },
  {
    name: 'Paneer (Cottage Cheese)',
    category: 'Dairy',
    servingSize: 100,
    servingUnit: 'g',
    calories: 265,
    protein: 18,
    carbohydrates: 3.5,
    fat: 20,
    fiber: 0,
    sugar: 2.5,
    saturatedFat: 12.0,
    sodium: 180,
    ingredients: [{ name: 'Milk' }, { name: 'Food-grade coagulant' }],
    benefits: ['Provides protein', 'Provides calcium', 'Provides phosphorus', 'Provides fat', 'Useful as a protein-rich vegetarian food'],
    nutrients: { Iron: 0.2, Calcium: 480, Potassium: 104, Magnesium: 18, Zinc: 1.5, 'Vitamin A': 90, 'Vitamin B6': 0.08, 'Vitamin B12': 0.8, Folate: 18, Selenium: 15 },
  },
  {
    name: 'Tofu',
    category: 'Plant Protein',
    servingSize: 100,
    servingUnit: 'g',
    calories: 76,
    protein: 8,
    carbohydrates: 1.9,
    fat: 4.8,
    fiber: 0.3,
    sugar: 0.4,
    saturatedFat: 0.7,
    sodium: 7,
    ingredients: [{ name: 'Soybeans' }, { name: 'Water' }, { name: 'Coagulant' }],
    benefits: ['Plant-based protein source', 'Provides iron', 'Provides calcium when calcium-set', 'Low in carbohydrates', 'Useful for vegetarian diets'],
    nutrients: { Iron: 5.4, Calcium: 350, Potassium: 121, Magnesium: 30, Zinc: 0.8 },
  },
  {
    name: 'Yellow Dal (Lentils)',
    category: 'Legumes',
    servingSize: 100,
    servingUnit: 'g cooked',
    calories: 116,
    protein: 9,
    carbohydrates: 20,
    fat: 0.4,
    fiber: 4,
    sugar: 1,
    saturatedFat: 0.1,
    sodium: 2,
    ingredients: [{ name: 'Lentils' }],
    benefits: ['Plant-based protein source', 'High in fiber', 'Provides iron', 'Provides folate', 'Provides complex carbohydrates'],
    nutrients: { Iron: 3.3, Calcium: 19, Potassium: 369, Magnesium: 36, Zinc: 1.3, 'Vitamin B6': 0.2, Folate: 181, Selenium: 2.8 },
  },
  {
    name: 'Chickpeas',
    category: 'Legumes',
    servingSize: 100,
    servingUnit: 'g cooked',
    calories: 164,
    protein: 8.9,
    carbohydrates: 27,
    fat: 2.6,
    fiber: 7.6,
    sugar: 4.8,
    saturatedFat: 0.3,
    sodium: 24,
    ingredients: [{ name: 'Chickpeas' }],
    benefits: ['Plant-based protein source', 'High in fiber', 'Provides folate', 'Provides iron', 'Provides complex carbohydrates'],
    nutrients: { Iron: 2.9, Calcium: 49, Potassium: 291, Magnesium: 48, Zinc: 1.5, Folate: 172 },
  },
  {
    name: 'Kidney Beans',
    category: 'Legumes',
    servingSize: 100,
    servingUnit: 'g cooked',
    calories: 127,
    protein: 8.7,
    carbohydrates: 22.8,
    fat: 0.5,
    fiber: 6.4,
    sugar: 0.3,
    saturatedFat: 0.1,
    sodium: 2,
    ingredients: [{ name: 'Kidney beans' }],
    benefits: ['Plant-based protein source', 'High in fiber', 'Provides folate', 'Provides iron', 'Provides potassium'],
    nutrients: { Iron: 2.9, Calcium: 28, Potassium: 405, Magnesium: 42, Zinc: 1.0, Folate: 130 },
  },
  {
    name: 'Rice (Cooked)',
    category: 'Grains',
    servingSize: 100,
    servingUnit: 'g',
    calories: 130,
    protein: 2.7,
    carbohydrates: 28,
    fat: 0.3,
    fiber: 0.4,
    sugar: 0.1,
    saturatedFat: 0.1,
    sodium: 1,
    ingredients: [{ name: 'White rice' }],
    benefits: ['Provides carbohydrates', 'Convenient energy source', 'Low in fat', 'Easy to combine with protein-rich foods', 'Provides manganese'],
    nutrients: { Iron: 0.2, Calcium: 10, Potassium: 35, Magnesium: 12, Zinc: 0.5, 'Vitamin B6': 0.1, Selenium: 7.5 },
  },
  {
    name: 'Brown Rice',
    category: 'Grains',
    servingSize: 100,
    servingUnit: 'g cooked',
    calories: 123,
    protein: 2.7,
    carbohydrates: 25.6,
    fat: 1.0,
    fiber: 1.6,
    sugar: 0.2,
    saturatedFat: 0.2,
    sodium: 1,
    ingredients: [{ name: 'Brown rice' }],
    benefits: ['Provides complex carbohydrates', 'Good source of fiber compared with white rice', 'Provides magnesium', 'Provides manganese', 'Useful as a whole-grain carbohydrate'],
    nutrients: { Iron: 0.5, Calcium: 10, Potassium: 86, Magnesium: 43, Zinc: 0.6 },
  },
  {
    name: 'Oats (Rolled)',
    category: 'Grains',
    servingSize: 100,
    servingUnit: 'g',
    calories: 389,
    protein: 16.9,
    carbohydrates: 66,
    fat: 6.9,
    fiber: 10.6,
    sugar: 1,
    saturatedFat: 1.2,
    sodium: 2,
    ingredients: [{ name: 'Whole oats' }],
    benefits: ['High in complex carbohydrates', 'Good source of fiber', 'Provides magnesium', 'Provides manganese', 'Can contribute to sustained meal energy'],
    nutrients: { Iron: 4.7, Calcium: 54, Potassium: 429, Magnesium: 177, Zinc: 4.0, 'Vitamin B6': 0.1, Folate: 56, Selenium: 28.9 },
  },
  {
    name: 'Whole Wheat Bread',
    category: 'Grains',
    servingSize: 100,
    servingUnit: 'g (3 slices)',
    calories: 265,
    protein: 9,
    carbohydrates: 49,
    fat: 3.2,
    fiber: 6,
    sugar: 5,
    saturatedFat: 0.7,
    sodium: 450,
    ingredients: [{ name: 'Whole wheat flour' }, { name: 'Water' }, { name: 'Yeast' }, { name: 'Salt' }],
    benefits: ['Provides carbohydrates', 'Provides fiber', 'Provides iron', 'Provides B vitamins', 'Convenient whole-grain option'],
    nutrients: { Iron: 2.5, Calcium: 161, Potassium: 250, Magnesium: 82, Zinc: 1.8, 'Vitamin B6': 0.2, Folate: 50, Selenium: 28 },
  },
  {
    name: 'Quinoa',
    category: 'Grains',
    servingSize: 100,
    servingUnit: 'g cooked',
    calories: 120,
    protein: 4.4,
    carbohydrates: 21.3,
    fat: 1.9,
    fiber: 2.8,
    sugar: 0.9,
    saturatedFat: 0.2,
    sodium: 7,
    ingredients: [{ name: 'Quinoa' }],
    benefits: ['Provides plant-based protein', 'Provides fiber', 'Provides magnesium', 'Provides iron', 'Provides complex carbohydrates'],
    nutrients: { Iron: 1.5, Calcium: 17, Potassium: 172, Magnesium: 64, Zinc: 1.1 },
  },
  {
    name: 'Sweet Potato',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'g',
    calories: 86,
    protein: 1.6,
    carbohydrates: 20,
    fat: 0.1,
    fiber: 3,
    sugar: 4.2,
    saturatedFat: 0.02,
    sodium: 55,
    ingredients: [{ name: 'Sweet potato' }],
    benefits: ['Provides carbohydrates', 'Rich source of beta-carotene', 'Provides fiber', 'Provides potassium', 'Provides vitamin C'],
    nutrients: { Iron: 0.6, Calcium: 30, Potassium: 337, Magnesium: 25, Zinc: 0.3, 'Vitamin A': 709, 'Vitamin C': 2.4, 'Vitamin B6': 0.2, Folate: 11, Selenium: 0.6 },
  },
  {
    name: 'Banana',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'g (1 medium)',
    calories: 89,
    protein: 1.1,
    carbohydrates: 23,
    fat: 0.3,
    fiber: 2.6,
    sugar: 12,
    saturatedFat: 0.1,
    sodium: 1,
    ingredients: [{ name: 'Banana' }],
    benefits: ['Provides carbohydrates', 'Provides potassium', 'Provides vitamin B6', 'Provides fiber', 'Convenient pre- or post-workout carbohydrate option'],
    nutrients: { Iron: 0.3, Calcium: 5, Potassium: 358, Magnesium: 27, Zinc: 0.1, 'Vitamin A': 3, 'Vitamin C': 8.7, 'Vitamin B6': 0.4, Folate: 20, Selenium: 1.0 },
  },
  {
    name: 'Apple',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'g (1 medium)',
    calories: 52,
    protein: 0.3,
    carbohydrates: 14,
    fat: 0.2,
    fiber: 2.4,
    sugar: 10,
    saturatedFat: 0.05,
    sodium: 1,
    ingredients: [{ name: 'Apple' }],
    benefits: ['Provides carbohydrates', 'Provides fiber', 'Provides vitamin C', 'Provides potassium', 'Convenient whole-fruit option'],
    nutrients: { Iron: 0.1, Calcium: 6, Potassium: 107, Magnesium: 5, Zinc: 0.04, 'Vitamin A': 3, 'Vitamin C': 4.6, 'Vitamin B6': 0.04, Folate: 3 },
  },
  {
    name: 'Orange',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'g (1 medium)',
    calories: 47,
    protein: 0.9,
    carbohydrates: 11.8,
    fat: 0.1,
    fiber: 2.4,
    sugar: 9.4,
    saturatedFat: 0.02,
    sodium: 0,
    ingredients: [{ name: 'Orange' }],
    benefits: ['Rich in vitamin C', 'Provides carbohydrates', 'Provides fiber', 'Provides folate', 'Provides potassium'],
    nutrients: { Iron: 0.1, Calcium: 40, Potassium: 181, Magnesium: 10, Zinc: 0.1, 'Vitamin C': 53.2, Folate: 30 },
  },
  {
    name: 'Blueberries',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'g',
    calories: 57,
    protein: 0.7,
    carbohydrates: 14.5,
    fat: 0.3,
    fiber: 2.4,
    sugar: 10,
    saturatedFat: 0.03,
    sodium: 1,
    ingredients: [{ name: 'Blueberries' }],
    benefits: ['Provides vitamin C', 'Provides vitamin K', 'Provides fiber', 'Provides manganese', 'Contains antioxidant compounds'],
    nutrients: { Iron: 0.3, Calcium: 6, Potassium: 77, Magnesium: 6, 'Vitamin C': 9.7, Folate: 6 },
  },
  {
    name: 'Broccoli',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'g',
    calories: 34,
    protein: 2.8,
    carbohydrates: 7,
    fat: 0.4,
    fiber: 2.6,
    sugar: 1.7,
    saturatedFat: 0.04,
    sodium: 33,
    ingredients: [{ name: 'Broccoli' }],
    benefits: ['Provides vitamin C', 'Provides vitamin K', 'Provides folate', 'Provides fiber', 'Provides potassium'],
    nutrients: { Iron: 0.7, Calcium: 47, Potassium: 316, Magnesium: 21, Zinc: 0.4, 'Vitamin A': 31, 'Vitamin C': 89.2, 'Vitamin B6': 0.2, Folate: 63, Selenium: 2.5 },
  },
  {
    name: 'Spinach',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'g',
    calories: 23,
    protein: 2.9,
    carbohydrates: 3.6,
    fat: 0.4,
    fiber: 2.2,
    sugar: 0.4,
    saturatedFat: 0.06,
    sodium: 79,
    ingredients: [{ name: 'Spinach' }],
    benefits: ['Provides folate', 'Provides vitamin K', 'Provides vitamin A', 'Provides iron', 'Provides magnesium'],
    nutrients: { Iron: 2.7, Calcium: 99, Potassium: 558, Magnesium: 79, Zinc: 0.5, 'Vitamin A': 469, 'Vitamin C': 28.1, 'Vitamin B6': 0.2, Folate: 194, Selenium: 1.0 },
  },
  {
    name: 'Carrot',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'g',
    calories: 41,
    protein: 0.9,
    carbohydrates: 9.6,
    fat: 0.2,
    fiber: 2.8,
    sugar: 4.7,
    saturatedFat: 0.04,
    sodium: 69,
    ingredients: [{ name: 'Carrot' }],
    benefits: ['Rich in beta-carotene', 'Provides fiber', 'Provides vitamin K', 'Provides potassium', 'Provides vitamin C'],
    nutrients: { Iron: 0.3, Calcium: 33, Potassium: 320, Magnesium: 12, 'Vitamin A': 835, 'Vitamin C': 5.9 },
  },
  {
    name: 'Tomato',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'g',
    calories: 18,
    protein: 0.9,
    carbohydrates: 3.9,
    fat: 0.2,
    fiber: 1.2,
    sugar: 2.6,
    saturatedFat: 0.03,
    sodium: 5,
    ingredients: [{ name: 'Tomato' }],
    benefits: ['Provides vitamin C', 'Provides potassium', 'Provides folate', 'Provides vitamin K', 'Contains lycopene'],
    nutrients: { Iron: 0.3, Calcium: 10, Potassium: 237, Magnesium: 11, 'Vitamin A': 42, 'Vitamin C': 13.7, Folate: 15 },
  },
  {
    name: 'Almonds',
    category: 'Nuts & Seeds',
    servingSize: 100,
    servingUnit: 'g (handful)',
    calories: 579,
    protein: 21,
    carbohydrates: 22,
    fat: 50,
    fiber: 12.5,
    sugar: 4.3,
    saturatedFat: 3.8,
    sodium: 1,
    ingredients: [{ name: 'Almonds' }],
    benefits: ['Provides healthy fats', 'Provides vitamin E', 'Provides magnesium', 'Provides protein', 'Provides fiber'],
    nutrients: { Iron: 3.7, Calcium: 269, Potassium: 733, Magnesium: 270, Zinc: 3.1, 'Vitamin B6': 0.1, Folate: 44, Selenium: 4.1 },
  },
  {
    name: 'Peanut Butter',
    category: 'Nuts & Spreads',
    servingSize: 100,
    servingUnit: 'g (3 tbsp)',
    calories: 588,
    protein: 25,
    carbohydrates: 20,
    fat: 50,
    fiber: 6,
    sugar: 9,
    saturatedFat: 10.0,
    sodium: 430,
    ingredients: [{ name: 'Peanuts' }, { name: 'Salt' }],
    benefits: ['Provides protein', 'Provides healthy fats', 'Provides magnesium', 'Provides vitamin E', 'Provides calories for energy intake'],
    nutrients: { Iron: 1.9, Calcium: 43, Potassium: 649, Magnesium: 168, Zinc: 2.9, 'Vitamin B6': 0.5, Folate: 86, Selenium: 5.6 },
  },
  {
    name: 'Walnuts',
    category: 'Nuts & Seeds',
    servingSize: 100,
    servingUnit: 'g',
    calories: 654,
    protein: 15.2,
    carbohydrates: 13.7,
    fat: 65.2,
    fiber: 6.7,
    sugar: 2.6,
    saturatedFat: 6.1,
    sodium: 2,
    ingredients: [{ name: 'Walnuts' }],
    benefits: ['Provides healthy fats', 'Provides omega-3 ALA', 'Provides magnesium', 'Provides copper', 'Provides fiber'],
    nutrients: { Iron: 2.9, Calcium: 98, Potassium: 441, Magnesium: 158, Zinc: 3.1 },
  },
  {
    name: 'Avocado',
    category: 'Fruits & Healthy Fats',
    servingSize: 100,
    servingUnit: 'g',
    calories: 160,
    protein: 2,
    carbohydrates: 8.5,
    fat: 14.7,
    fiber: 6.7,
    sugar: 0.7,
    saturatedFat: 2.1,
    sodium: 7,
    ingredients: [{ name: 'Avocado' }],
    benefits: ['Provides monounsaturated fats', 'High in fiber', 'Provides potassium', 'Provides folate', 'Provides vitamin E'],
    nutrients: { Iron: 0.6, Calcium: 12, Potassium: 485, Magnesium: 29, Zinc: 0.6, Folate: 81 },
  },
  {
    name: 'Whole Milk',
    category: 'Dairy',
    servingSize: 100,
    servingUnit: 'ml',
    calories: 60,
    protein: 3.2,
    carbohydrates: 4.8,
    fat: 3.2,
    fiber: 0,
    sugar: 5,
    saturatedFat: 1.9,
    sodium: 43,
    ingredients: [{ name: 'Milk' }],
    benefits: ['Provides protein', 'Provides calcium', 'Provides vitamin B12', 'Provides phosphorus', 'Provides potassium'],
    nutrients: { Iron: 0.03, Calcium: 113, Potassium: 132, Magnesium: 10, Zinc: 0.4, 'Vitamin A': 46, 'Vitamin D': 1.3, 'Vitamin B6': 0.04, 'Vitamin B12': 0.45, Folate: 5, Selenium: 3.7 },
  },
  {
    name: 'Cottage Cheese',
    category: 'Dairy',
    servingSize: 100,
    servingUnit: 'g',
    calories: 98,
    protein: 11.1,
    carbohydrates: 3.4,
    fat: 4.3,
    fiber: 0,
    sugar: 2.7,
    saturatedFat: 1.7,
    sodium: 364,
    ingredients: [{ name: 'Milk' }, { name: 'Cultures' }, { name: 'Salt' }],
    benefits: ['High in protein', 'Provides calcium', 'Provides phosphorus', 'Provides vitamin B12', 'Useful for increasing protein intake'],
    nutrients: { Iron: 0.1, Calcium: 83, Potassium: 104, Magnesium: 8, Zinc: 0.4, 'Vitamin B12': 0.43 },
  },
];

async function main() {
  console.log(`Seeding exercises into MySQL...`);
  let exCount = 0;
  for (const ex of exercises) {
    let mg = ex.category;
    if (mg === 'LEGS') mg = 'QUADS';
    if (mg === 'ARMS') mg = 'BICEPS';

    const exercisePayload: any = {
      name: ex.name,
      slug: ex.slug,
      muscleGroup: mg as any,
      category: ex.category,
      equipment: ex.equipment as any,
      difficulty: ex.difficulty as any,
      description: ex.instructions,
      instructions: ex.instructions,
      primaryMuscle: ex.targetMuscles,
      setsRecommendation: 3,
      repsRecommendation: ex.repsRecommendation || '8-12',
      restSeconds: ex.restSeconds,
      caloriesBurnEstimate: ex.caloriesBurnEstimate,
    };

    await prisma.exercise.upsert({
      where: { slug: ex.slug },
      update: exercisePayload,
      create: exercisePayload,
    });
    exCount++;
  }
  console.log(`Successfully updated ${exCount} exercises in MySQL!`);

  console.log(`Seeding reference nutrients into MySQL...`);
  const nutrientMap: Record<string, string> = {};
  for (const n of nutrients) {
    const created = await prisma.nutrient.upsert({
      where: { name: n.name },
      update: n,
      create: n,
    });
    nutrientMap[n.name] = created.id;
  }
  console.log(`Successfully updated ${Object.keys(nutrientMap).length} reference nutrients in MySQL!`);

  console.log(`Seeding 30 food items with micronutrients, ingredients, and benefits into MySQL...`);
  let foodCount = 0;
  for (const foodData of foods) {
    const { nutrients: foodNutrientMap, ingredients: foodIngs, benefits: foodBens, ...coreFood } = foodData;
    const food = await prisma.food.upsert({
      where: { name: coreFood.name },
      update: coreFood,
      create: coreFood,
    });

    // Seed Micronutrients
    if (foodNutrientMap) {
      for (const [nutrientName, amount] of Object.entries(foodNutrientMap)) {
        const nutrientId = nutrientMap[nutrientName];
        if (nutrientId) {
          await prisma.foodNutrient.upsert({
            where: {
              foodId_nutrientId: {
                foodId: food.id,
                nutrientId,
              },
            },
            update: { amount: Number(amount) },
            create: {
              foodId: food.id,
              nutrientId,
              amount: Number(amount),
            },
          });
        }
      }
    }

    // Seed Ingredients
    if (foodIngs && foodIngs.length > 0) {
      await prisma.foodIngredient.deleteMany({ where: { foodId: food.id } });
      for (let i = 0; i < foodIngs.length; i++) {
        await prisma.foodIngredient.create({
          data: {
            foodId: food.id,
            name: foodIngs[i].name,
            sortOrder: i + 1,
          },
        });
      }
    }

    // Seed Benefits
    if (foodBens && foodBens.length > 0) {
      await prisma.foodBenefit.deleteMany({ where: { foodId: food.id } });
      for (let i = 0; i < foodBens.length; i++) {
        await prisma.foodBenefit.create({
          data: {
            foodId: food.id,
            benefit: foodBens[i],
            sortOrder: i + 1,
          },
        });
      }
    }

    foodCount++;
  }
  console.log(`Successfully seeded ${foodCount} foods with ingredients and benefits in MySQL!`);
}

main()
  .catch((e) => {
    console.error('Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
